M48
; DRILL file {KiCad 9.0.2} date 2025-06-06T06:26:32-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-06T06:26:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X138.19Y-168.0
T2
X214.5Y-149.0
X219.5Y-144.0
X219.5Y-154.0
X222.0Y-144.0
X222.0Y-154.0
T3
X139.0Y-64.0
M30
